version: 0.2

env:
  secrets-manager:
    DOCKER_TOKEN: "tokens:dockerToken"
    DOCKER_ECR: "core:dockerEcr"
    DOCKER_USER: "core:dockerUser"
    REPO: "scheduler:repository"
    BUCKET_PATH: "scheduler:filesBucketPath"
    TASK_DEFINITION_ARN: "scheduler:TASK_DEFINITION_ARN"
    EXECUTION_ROLE_ARN: "scheduler:EXECUTION_ROLE_ARN"
    TASK_DEFINITION_NAME: "scheduler:TASK_DEFINITION_NAME"
    DATABASE_URL: "scheduler:DATABASE_URL"
    NEXT_PUBLIC_WEBAPP_URL: "scheduler:NEXT_PUBLIC_WEBAPP_URL"
    NEXT_PUBLIC_WEBSITE_URL: "scheduler:NEXT_PUBLIC_WEBSITE_URL"
    NEXT_PUBLIC_CONSOLE_URL: "scheduler:NEXT_PUBLIC_CONSOLE_URL"
    NEXT_PUBLIC_EMBED_LIB_URL: "scheduler:NEXT_PUBLIC_EMBED_LIB_URL"
    CRON_API_KEY: "scheduler:CRON_API_KEY"
    CALENDSO_ENCRYPTION_KEY: "scheduler:CALENDSO_ENCRYPTION_KEY"
    SENDGRID_API_KEY: "scheduler:SENDGRID_API_KEY"
    SENDGRID_EMAIL: "scheduler:SENDGRID_EMAIL"
    NEXT_PUBLIC_SENDGRID_SENDER_NAME: "scheduler:NEXT_PUBLIC_SENDGRID_SENDER_NAME"
    TWILIO_SID: "scheduler:TWILIO_SID"
    TWILIO_TOKEN: "scheduler:TWILIO_TOKEN"
    TWILIO_MESSAGING_SID: "scheduler:TWILIO_MESSAGING_SID"
    TWILIO_PHONE_NUMBER: "scheduler:TWILIO_PHONE_NUMBER"
    NEXT_PUBLIC_SENDER_ID: "scheduler:NEXT_PUBLIC_SENDER_ID"
    TWILIO_VERIFY_SID: "scheduler:TWILIO_VERIFY_SID"
    EMAIL_FROM: "scheduler:EMAIL_FROM"
    EMAIL_SERVER_HOST: "scheduler:EMAIL_SERVER_HOST"
    EMAIL_SERVER_USER: "scheduler:EMAIL_SERVER_USER"
    EMAIL_SERVER_PASSWORD: "scheduler:EMAIL_SERVER_PASSWORD"
    NEXT_PUBLIC_APP_NAME: "scheduler:NEXT_PUBLIC_APP_NAME"
    NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS: "scheduler:NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS"
    NEXT_PUBLIC_COMPANY_NAME: "scheduler:NEXT_PUBLIC_COMPANY_NAME"
    GOOGLE_API_CREDENTIALS: "scheduler:GOOGLE_API_CREDENTIALS"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $DOCKER_ECR
      - REPOSITORY_URI=$REPO
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    on-failure: ABORT
    commands:
      - echo Build started on `date`
      - echo Logging into Docker...
      - echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
      - echo Pulling docker node:current-bullseye-slim image...
      - docker pull node:current-bullseye-slim
      - echo Copying required files
      - cp .env.example .env
      - sed -i 's/TASK_DEFINITION_ARN/$TASK_DEFINITION_ARN/g' taskdef.json
      - sed -i 's/EXECUTION_ROLE_ARN /$EXECUTION_ROLE_ARN/g' taskdef.json
      - sed -i 's/TASK_DEFINITION_NAME/$TASK_DEFINITION_NAME/g' taskdef.json
      - cat taskdef.json
      - sed -i '/DATABASE_URL/s/.*/DATABASE_URL="${DATABASE_URL}"/' .env
      - sed -i '/NEXT_PUBLIC_WEBAPP_URL/s/.*/NEXT_PUBLIC_WEBAPP_URL="${NEXT_PUBLIC_WEBAPP_URL}"/' .env
      - sed -i '/NEXT_PUBLIC_WEBSITE_URL/s/.*/NEXT_PUBLIC_WEBSITE_URL="${NEXT_PUBLIC_WEBSITE_URL}"/' .env
      - sed -i '/NEXT_PUBLIC_CONSOLE_URL/s/.*/NEXT_PUBLIC_CONSOLE_URL="${NEXT_PUBLIC_CONSOLE_URL}"/' .env
      - sed -i '/NEXT_PUBLIC_EMBED_LIB_URL/s/.*/NEXT_PUBLIC_EMBED_LIB_URL="${NEXT_PUBLIC_EMBED_LIB_URL}"/' .env
      - sed -i '/CRON_API_KEY/s/.*/CRON_API_KEY="${CRON_API_KEY}"/' .env
      - sed -i '/CALENDSO_ENCRYPTION_KEY/s/.*/CALENDSO_ENCRYPTION_KEY="${CALENDSO_ENCRYPTION_KEY}"/' .env
      - sed -i '/SENDGRID_API_KEY/s/.*/SENDGRID_API_KEY="${SENDGRID_API_KEY}"/' .env
      - sed -i '/SENDGRID_EMAIL/s/.*/SENDGRID_EMAIL="${SENDGRID_EMAIL}"/' .env
      - sed -i '/NEXT_PUBLIC_SENDGRID_SENDER_NAME/s/.*/NEXT_PUBLIC_SENDGRID_SENDER_NAME="${NEXT_PUBLIC_SENDGRID_SENDER_NAME}"/' .env
      - sed -i '/TWILIO_SID/s/.*/TWILIO_SID="${TWILIO_SID}"/' .env
      - sed -i '/TWILIO_TOKEN/s/.*/TWILIO_TOKEN="${TWILIO_TOKEN}"/' .env
      - sed -i '/TWILIO_MESSAGING_SID/s/.*/TWILIO_MESSAGING_SID="${TWILIO_MESSAGING_SID}"/' .env
      - sed -i '/TWILIO_PHONE_NUMBER/s/.*/TWILIO_PHONE_NUMBER="${TWILIO_PHONE_NUMBER}"/' .env
      - sed -i '/NEXT_PUBLIC_SENDER_ID/s/.*/NEXT_PUBLIC_SENDER_ID="${NEXT_PUBLIC_SENDER_ID}"/' .env
      - sed -i '/TWILIO_VERIFY_SID/s/.*/TWILIO_VERIFY_SID="${TWILIO_VERIFY_SID}"/' .env
      - sed -i '/EMAIL_FROM/s/.*/EMAIL_FROM="${EMAIL_FROM}"/' .env
      - sed -i '/EMAIL_SERVER_HOST/s/.*/EMAIL_SERVER_HOST="${EMAIL_SERVER_HOST}"/' .env
      - sed -i '/EMAIL_SERVER_USER/s/.*/EMAIL_SERVER_USER="${EMAIL_SERVER_USER}"/' .env
      - sed -i '/EMAIL_SERVER_PASSWORD/s/.*/EMAIL_SERVER_PASSWORD="${EMAIL_SERVER_PASSWORD}"/' .env
      - sed -i '/NEXT_PUBLIC_APP_NAME/s/.*/NEXT_PUBLIC_APP_NAME="${NEXT_PUBLIC_APP_NAME}"/' .env
      - sed -i '/NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS/s/.*/NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS="${NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS}"/' .env
      - sed -i '/NEXT_PUBLIC_COMPANY_NAME/s/.*/NEXT_PUBLIC_COMPANY_NAME="${NEXT_PUBLIC_COMPANY_NAME}"/' .env
      - echo "\n\nGOOGLE_API_CREDENTIALS='${GOOGLE_API_CREDENTIALS}'" >> .env
      - cat .env
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - echo Docker respository URI is $REPOSITORY_URI
      - echo Docker image tag URI is $IMAGE_TAG
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files:
    - "image*.json"
    - "appspec.yaml"
    - "taskdef.json"
  secondary-artifacts:
    DefinitionArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
