apiVersion: apps/v1
kind: Deployment
metadata:
   name: {{.Chart.Name}}
   namespace: {{ .Values.namespace }}
spec:
   replicas: {{ .Values.replicas }}
   selector:
      matchLabels:
         app: {{.Chart.Name}}
   template:
      metadata:
         labels:
            app: {{.Chart.Name}}
      spec:
         containers:
            - name: {{.Chart.Name}}
              image:  "{{.Values.registry}}.azurecr.io/{{.Values.respository}}:v1"
              ports:
                 - containerPort: {{ .Values.appPort }}
              env:
                 - name: TITLE
                   value: "{{.Values.title}}"
              readinessProbe:
               tcpSocket:
                 port: {{ .Values.appPort }}
               initialDelaySeconds: 10
               periodSeconds: 10
              livenessProbe:
               tcpSocket:
                 port: {{ .Values.appPort }}
               initialDelaySeconds: 10
               periodSeconds: 30