apiVersion: v1
kind: Service
metadata:
   name: "{{ .Chart.Name }}-service"
   namespace: {{ .Release.Namespace }}
spec:
   type: {{ .Values.serviceType }}
   ports:
      - protocol: TCP
        port: 80
        targetPort: {{ .Values.appPort }}
   selector:
      app: {{ .Chart.Name }}
