apiVersion: v1
kind: Service
metadata:
   name: "{{ .Chart.Name }}-service"
   labels:
      app: {{.Chart.Name}}
   namespace: {{ .Values.namespace }}
   annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
   type: {{ .Values.serviceType }}
   ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: {{ .Values.appPort }}
   selector:
      app: {{ .Chart.Name }}
