apiVersion: v1
kind: Service
metadata:
   name: {{ .Chart.Name }}
   namespace: {{ .Release.Namespace }}
spec:
   type: {{ .Values.serviceType }}
   ports:
      - port: 80
        targetPort: 3000
   selector:
      app: "{{.Chart.Name}}-{{.Release.Name}}"
